server:
  port: 8101

spring:
  application:
    name: eureka-client-1
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1 #设置Sleuth的抽样收集概率

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8033/eureka/,http://eurekaserver02:8034/eureka/,http://eurekaserver03:8035/eureka/
  instance:
    prefer-ip-address: true
    instance-id: eureka-client-1
info:
  app.name: eureka-client-1
  company.name: www.eurekacilent.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$