server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8033/eureka/,http://eurekaserver02:8034/eureka/,http://eurekaserver03:8035/eureka/
spring:
  application:
    name: cloud-ribbon
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1 #设置Sleuth的抽样收集概率
