server:
  port: 8033
eureka:
  instance:
    hostname: eurekaserver
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eurekaserver03:8035/eureka/,http://eurekaserver02:8034/eureka/