server:
  port: 88

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8033/eureka/,http://eurekaserver02:8034/eureka/,http://eurekaserver03:8035/eureka/
spring:
  application:
    name: cloud-feign


ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  SocketTimeout: 5000
