server:
  port: 88

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver:8033/eureka/,http://eurekaserver02:8034/eureka/,http://eurekaserver03:8035/eureka/
spring:
  application:
    name: cloud-feign
