server:
  port: 9001

spring:
  application:
    name: zuul-getaway
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8033/eureka/,http://eurekaserver02:8034/eureka/,http://eurekaserver03:8035/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client-1
    api-b:
      path: /api-b/**
      serviceId: eureka-client-2

